---
version: 2

project_name: speedtest_exporter

before:
  hooks:
    - go mod tidy

builds:
  - id: binaries
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: main.go
    ldflags:
      - "-X github.com/veerendra2/gopackages/version.Version={{.Version}}"
      - "-X github.com/veerendra2/gopackages/version.Revision={{.ShortCommit}}"
      - "-X github.com/veerendra2/gopackages/version.Branch={{.Branch}}"
      - "-X github.com/veerendra2/gopackages/version.BuildUser={{if .Env.USER}}{{.Env.USER}}{{else}}ci{{end}}"
      - "-X github.com/veerendra2/gopackages/version.BuildDate={{.Date}}"

kos:
  - id: distroless-image
    build: binaries
    repositories:
      - ghcr.io/veerendra2/speedtest_exporter
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
      - darwin/amd64
      - darwin/arm64
    base_image: gcr.io/distroless/static:nonroot

archives:
  - formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
