---
name: speedtest_exporter
services:
  speedtest_exporter:
    image: ghcr.io/veerendra2/speedtest_exporter:latest
    container_name: speedtest_exporter
    ports:
      - '8080:8080'
    restart: unless-stopped
    hostname: speedtest_exporter
