{
 "title": "Speedtest",
 "description": "Speedtest Exporter Dashboard - https://github.com/veerendra2/speedtest_exporter",
 "tags": [ "speedtest" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Download Speed",
   "type": "gauge",
   "description": "Average download speed",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(speedtest_download_speed_bps[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "description": "Average upload speed",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "speedtest_upload_speed_bps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "description": "Mean latency in selected time window",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "speedtest_latency_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "speedtest_latency_seconds", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Speedtest Duration",
   "type": "timeseries",
   "description": "Speedtest duration",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "speedtest_scrape_duration_seconds",
     "legendFormat": "Test Duration"
    }
   ]
  },
  {
   "title": "Download/Upload Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "speedtest_download_speed_bps", "legendFormat": "Download" },
    { "expr": "speedtest_upload_speed_bps", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "Speedtest History",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 15 },
   "targets": [
    { "expr": "speedtest_status[$__interval]", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Speedtest User & Server Locations",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 15 },
   "targets": [
    { "expr": "speedtest_status", "legendFormat": "__auto" }
   ]
  }
 ]
}